dist: trusty
language: c
compiler: gcc
cache: ccache
env:
  - ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOCALVERSION=-git$TRAVIS_COMMIT
addons:
  apt:
    packages:
    - debootstrap
    - qemu-user-static
    - binfmt-support
    - sbuild
    - lzop
before_script:
  - wget -c https://releases.linaro.org/components/toolchain/binaries/5.3-2016.02/arm-linux-gnueabihf/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xf gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf.tar.xz
  - export PATH=$PATH:$PWD/gcc-linaro-5.3-2016.02-x86_64_arm-linux-gnueabihf/bin/
  - arm-linux-gnueabihf-gcc --version  
  - sudo apt-get install bc
script:
  - bash -ex build_deb_in_arm_chroot.sh
